Repository javidsegura/CasinoMines, pull requests merged in 2024-11, with the labels that each got.

#26 Update README.md
  README.md
Labels: Review effort [1-5]: 1

#31 Changes to grid.py, game_css.py and icons under cells
  src/board/__pycache__/grid.cpython-311.pyc
  src/board/__pycache__/header.cpython-311.pyc
  src/board/__pycache__/mines.cpython-311.pyc
  src/board/__pycache__/settings.cpython-311.pyc
  src/board/grid.py
  src/design/__pycache__/game_css.cpython-311.pyc
  src/design/game_css.py
  src/game_tabs/__pycache__/data.cpython-311.pyc
  src/game_tabs/__pycache__/game_stats_ui.cpython-311.pyc
  src/game_tabs/__pycache__/leaderboard_ui.cpython-311.pyc
  src/game_tabs/__pycache__/payout.cpython-311.pyc
  src/others/__pycache__/confetty.cpython-311.pyc
  src/others/__pycache__/login_dialog.cpython-311.pyc
  src/others/__pycache__/multiplier.cpython-311.pyc
  src/others/__pycache__/sound_effects.cpython-311.pyc
  src/others/__pycache__/wallet.cpython-311.pyc
  src/others/algorithms/__pycache__/searching.cpython-311.pyc
  src/others/algorithms/__pycache__/sorting.cpython-311.pyc
  utils/imgs/cells/bomb.png
  utils/imgs/cells/doubt.png
  utils/imgs/cells/star.png
  utils/imgs/cells/treasure.png
Labels: Review effort [1-5]: 2

#35 Boris
  .DS_Store
  src/board/__pycache__/grid.cpython-311.pyc
  src/board/__pycache__/header.cpython-311.pyc
  src/board/__pycache__/mines.cpython-311.pyc
  src/board/__pycache__/settings.cpython-311.pyc
  src/design/__pycache__/game_css.cpython-311.pyc
  src/game_tabs/__pycache__/data.cpython-311.pyc
  src/game_tabs/__pycache__/game_stats_ui.cpython-311.pyc
  src/game_tabs/__pycache__/leaderboard_ui.cpython-311.pyc
  src/game_tabs/__pycache__/payout.cpython-311.pyc
  src/game_tabs/data.py
  src/game_tabs/game_stats_ui.py
  src/game_tabs/leaderboard_ui.py
  src/main.py
  src/others/__pycache__/confetty.cpython-311.pyc
  src/others/__pycache__/login_dialog.cpython-311.pyc
  src/others/__pycache__/multiplier.cpython-311.pyc
  src/others/__pycache__/sound_effects.cpython-311.pyc
  src/others/__pycache__/wallet.cpython-311.pyc
  src/others/algorithms/__pycache__/searching.cpython-311.pyc
  src/others/algorithms/__pycache__/sorting.cpython-311.pyc
  src/others/algorithms/searching.py
  src/others/algorithms/sorting.py
  src/others/login_dialog.py
  utils/data/game_stats.csv
  utils/imgs/canvas.png
  utils/imgs/podium.png
Labels: Review effort [1-5]: 4

#36 Cayetana
  .DS_Store
  README.md
Labels: Review effort [1-5]: 1

#37 others folder complexities
  src/others/confetty.py
  src/others/login_dialog.py
  src/others/multiplier.py
  src/others/simulateGame.py
  src/others/sound_effects.py
  src/others/wallet.py
Labels: Review effort [1-5]: 2

#38 header.py and mines.py complexities
  src/board/header.py
  src/board/mines.py
Labels: Review effort [1-5]: 1

#39 new podium
  src/game_tabs/data.py
  src/game_tabs/leaderboard_ui.py
Labels: Review effort [1-5]: 2

#40 Documentation boris
  src/game_tabs/game_stats_ui.py
  src/game_tabs/leaderboard_ui.py
Labels: Review effort [1-5]: 2
